---
- name: Create ssh key directory
  file:
    state: directory
    owner: root
    group: root
    mode: 0755
    path: "{{ ssh_key_directory }}"

- name: Add and remove ssh pub key for users
  authorized_key:
    user: "{{ item.user }}"
    key: "{% if item.file is defined %}{{ lookup('file', item.file) }}{% else %}{{ item.key }}{% endif %}"
    key_options: "{{ item.key_options|default('') }}"
    state: "{{ item.state|default('present') }}"
    path: "{{ ssh_key_directory }}/{{ item.user }}"
    manage_dir: "no"
  with_items: "{{ ssh_keys }}"
  when: item.key is defined or item.file is defined
  # Don't spam verbose log with this output
  no_log: true

- name: Fix ssh pub key permissions
  file:
    path: "{{ ssh_key_directory }}/{{ item.user }}"
    state: file
    owner: root
    group: root
    mode: 0444
  with_items: "{{ ssh_keys }}"
  when: item.state|default('present') != 'absent'
