---
- name: Create ssh key directory
  file:
    state: directory
    owner: root
    group: root
    mode: 0644
    path: "{{ ssh_key_directory }}"

- name: Add ssh pub key for users
  authorized_key:
    user: "{{ item.user }}"
    key: "{{ item.key|default(lookup('file', item.file)) }}"
    state: "{{ item.state|default('present') }}"
    path: "/etc/ssh/authorized_keys/{{ item.name }}"
    manage_dir: "no"
  with_items: "{{ ssh_keys }}"
  when: item.file is defined or item.key is defined

- name: Fix ssh pub key permissions
  file:
    path: "/etc/ssh/authorized_keys/{{ item.name }}"
    state: file
    owner: root
    group: root
    mode: 0444
  with_items: "{{ ssh_keys }}"
